#!/bin/sh

D_MAX_TOTAL_LENGTH_=8192
D_RETURN_S_AXILITE_=1
D_RETURN_AP_CTRL_HS_=0
D_TOP_=$(cat ../TOP)

CFLAGS=""
CFLAGS="$CFLAGS -DD_MAX_TOTAL_LENGTH_=$D_MAX_TOTAL_LENGTH_"
CFLAGS="$CFLAGS -DD_RETURN_S_AXILITE_=$D_RETURN_S_AXILITE_"
CFLAGS="$CFLAGS -DD_RETURN_AP_CTRL_HS_=$D_RETURN_AP_CTRL_HS_"
CFLAGS="$CFLAGS -DD_TOP_=$D_TOP_"
